### ISSUE TITLE
Make me owner of the project

### ISSUE THREAD

**Issue by tobyplowy** [minetest-texturepacks/gmc_extras#8]
@tacotexmex Can You Make Me owner of the Project so we can keep it updated?

**Comment by tacotexmex** [comment]
You're already a member of the organization and I've now given you write access to the repo. Good luck!

**Comment by tobyplowy** [comment]
@tacotexmex thanks :)

**Comment by tobyplowy** [comment]
@tacotexmex can you do the same for https://github.com/minetest-texturepacks/Good-Morning-Craft-Minetest/issues

Also it seems like you are not updateing this pack anymore why

**Comment by tacotexmex** [comment]
You're now a contributor for both GMC and gmc_extras.

I stopped because I don't have time and focus for Minetest anymore. I'd be glad if you choose to continue it of course.

**Comment by tobyplowy** [comment]
> I'd be glad if you choose to continue it of course.

It's going to be a low priority 
Because I have vanilla 32x Summerfields and farlands and maybe epic adventures to keep updated 
But I will see what I can do
